# INDIVISUAL COLLUM DISPLAY
QUARY  = "SELECT DISTINCT BOOK_NAME FROM BOOK "


# WHERE FUNCTION
QUARY  = "SELECT * FROM  BOOK WHERE BOOK_ID=1 "


# AND FUNCTION 
QUARY  = "SELECT * FROM  BOOK WHERE BOOK_ID=1 AND BOOK_NAME='C++' "


# OR FUNCTION 
QUARY  = "SELECT * FROM  BOOK WHERE BOOK_NAME='JAVA' OR BOOK_NAME='C++' "


# IN FUNCTION 
QUARY  = "SELECT BOOK_ID,BOOK_NAME FROM  BOOK WHERE BOOK_NAME IN ('C++','PYTHON') "


# IN FUNCTION 
QUARY  = "SELECT BOOK_ID,BOOK_NAME FROM  BOOK WHERE BOOK_NAME IN ('C++','PYTHON') "


# BETWEEN FUNCTION 
QUARY  = "SELECT BOOK_ID,BOOK_NAME FROM  BOOK WHERE PRICE BETWEEN 200 AND 500 "


# INNER JOIN FUNCTION 
QUARY  = "SELECT BOOK_ID,BOOK_NAME FROM  BOOK INNER JOIN TABLE2 ON BOOK.TABLE2_ID=TABLE2.TABLE2_ID "


# LEFT JOIN FUNCTION 
QUARY  = "SELECT T1.C1,T2.C2 FROM TABLE T1 LEFT JOIN TABLE T2 ON T1.C1=T2.C2 "


# RIGHT JOIN FUNCTION 
QUARY  = "SELECT T1.C1,T2.C2 FROM TABLE T1 LEFT JOIN TABLE T2 ON T1.C1=T2.C1 "


# CROSS JOIN FUNCTION 
QUARY  = "SELECT * FROM T1 CROSS JOIN T2 "

